### PR TITLE
Create a blank chapter called ray theory: travel times

### PR DESCRIPTION
**Pull request by core-man**
#1 & #7.

### CODE REVIEW

**Comment by seisman** [comment]
Do we really need a whole chapter for ray nomenclature?

**Comment by core-man** [comment]
> Do we really need a whole chapter for ray nomenclature?

That depends on how we define a chapter. Now I mean "射线理论：走时" is a chapter (chapter 4 in Peter's book), while "射线命名规则" is a section (4.7 in Peter's book). "ray-nomenclature“ is a folder and contain some rst files.

Do we want to put a "ray-nomenclature" folder under the folder "ray-theory-traveltime" instead?

content

**Comment by seisman** [comment]
> "射线理论：走时" is a chapter (chapter 4 in Peter's book), while "射线命名规则" is a section (4.7 in Peter's book)

Then the sidebar will be too long (longer than one screen page) as all sections will be shown.

**Comment by core-man** [comment]
> > "射线理论：走时" is a chapter (chapter 4 in Peter's book), while "射线命名规则" is a section (4.7 in Peter's book)
> 
> Then the sidebar will be too long (longer than one screen page) as all sections will be shown.

Yes, actually this is the same question we talked about in software repo.

**Comment by seisman** [comment]
> > > "射线理论：走时" is a chapter (chapter 4 in Peter's book), while "射线命名规则" is a section (4.7 in Peter's book)
> > 
> > 
> > Then the sidebar will be too long (longer than one screen page) as all sections will be shown.
> 
> Yes, actually this is the same question we talked about in software repo.

It's slightly different. We may not have more than 30 software, But we will have>30 sections.

**Comment by seisman** [comment]
We can keep it open and think more about it. Or we can merge it and resturcture it later. I'm ok to both

**Comment by core-man** [comment]
> We can keep it open and think more about it. Or we can merge it and resturcture it later. I'm ok to both

@seisman ，How about merging it so that we can move on? Now, I made a folder called "ray-theory-travel-times" for the chapter and also made a subfolder for the section "ray nomenclature".

**Comment by core-man** [comment]
Any more suggestion?

**Review by seisman — APPROVED** [review]

**Pull request merged**
